# Generated by Django 5.1.5 on 2025-02-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0002_rename_addtask_addtask_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
